name: linearEqn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.20.3
  - scipy
  - matplotlib
  - pillow
  - h5py
  - opencv
  - flask
  - tensorflow=2.5
  - scikit-image
  - scikit-learn
  - pip:
      - imageio
      - keras-preprocessing
      - tqdm
      - requests